name: Solr Core Creation

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t my_solr_image .

    - name: Run Docker container
      run: docker run -d -p 8983:8983 --name adc my_solr_image

    - name: Create Solr core
      run: |
        sleep 30 # Give Solr some time to start
        docker exec adc solr create_core -c adc -d /var/solr/data/configsets/adc || exit 1
    - name: Ingest test docuement
      run: |
        sleep 5 # Give Solr some time to start
        idocker exec adc solr post -c adc -out -verbose example_mmd_solr_drupal8.json || exit 1
