name: Solr Core Creation

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-solr-schema:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v6

    - name: Setup Apache Solr Infrastructure
      uses: dhavalgojiya/setup-solr-action@v1
      with:
        solr-version: "9.10.0"
        solr-core-name: "test"
        solr-custom-configset-path: "conf/"
    - name: Add test document
      run: |
        curl --fail --show-error --silent \
        -X POST "http://localhost:8983/solr/test/update?commit=true" \
        -H "Content-Type: application/json" \
        --data-binary @example_mmd_solr.json
